export type {
    AgentCard,
    AgentSkill,
    DataMessagePart,
    FileMessagePart,
    JsonRpcError,
    JsonRpcErrorResponse,
    JsonRpcRequest,
    JsonRpcResponse,
    JsonRpcSuccessResponse,
    Message,
    MessagePart,
    MessageSendParams,
    MessageSendResponse,
    Task,
    TaskStatus,
    TaskStatusState,
    TextMessagePart,
} from './a2a.vo';
